apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: demo
spec:
  containers:
  - name: ubuntu
    image: ubuntu:trusty
    command: ["echo"]
    args: ["Hello World"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"

  restartPolicy: Never